# -*- coding: utf-8 -*-
"""Voice_Assistant_AGC ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0ITM8GcvC8PTNmexSXwL5MU6A-5LFkk
"""

from openai import OpenAI

from google.colab import userdata
userdata.get('Voice_Assist')

client = OpenAI(api_key=userdata.get('Voice_Assist'))

response = client.responses.create(
  prompt={
    "id": "pmpt_69410f8c488481958718fcd6c481159b0e2d27390a992a6d",
    "version": "4"
  },
  input=[],
  text={
    "format": {
      "type": "text"
    }
  },
  reasoning={},
  tools=[
    {
      "type": "file_search",
      "vector_store_ids": [
        "vs_694108c097a08191ad00d7e0dee577af"
      ]
    }
  ],
  max_output_tokens=2048,
  store=True,
  include=["web_search_call.action.sources"]
)







